baseURL = "https://diazvictor.github.io/"
languageCode = "es"
publishDir = "public"
title = "diazvictor"
disqusShortname = "diazvictor"
theme = "blue-ocean"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

[params]
author = "Víctor Díaz"
subtitle = "DESARROLLO WEB Y APLICACIONES"
description = "Dedicado al desarrollo web y aplicaciones, enamorado de lua."
copyright = "© 2021"
keywords = "blog, developer, personal"
avatar = "/images/favicon.png"
mainSections = ["post"]
dateFormat = "2 January, 2006"
readTime_post = true
recent_num = 5

[menu]
	[[menu.item]]
	name = "BLOG"
    url = "/post"
    weight = 1

	[[menu.item]]
	name = "ABOUT"
    url = "/about"
    weight = 2

[params.sidebar]
sidebar = true
widgets = ["aboutbox", "recent", "categories", "taglist"]

[params.widgets]
aboutbox_description = "Desarrollador web y desktop con conocimientos (backend/frontend) en lenguajes Lua, Php, SQL (SQLite), HTML, CSS y Javascript."
recent_num = 5 # Set the number of articles in the "Recent articles" widget
scrolltop = true
social_footer = true

[[params.social]]
	name = "GITHUB"
	icon = "fab fa-github-alt"
	color = "is-link"
    weight = 1
    url = "https://github.com/diazvictor/"

[[params.social]]
	name = "TELEGRAM"
	icon = "fab fa-telegram"
	color = "is-link"
    weight = 1
    url = "https://t.me/diazvictor"

[[params.social]]
	name = "MASTODON"
	icon = "fab fa-mastodon"
	color = "is-link"
    weight = 1
    url = "https://mas.to/@diazvictor"

[[params.social]]
	name = "MAIL"
	icon = "fas fa-envelope"
	color = "is-link"
    weight = 1
    url = "mailto:victor.vector008@gmail.com"

[[params.social]]
	name = "GITLAB"
	icon = "fab fa-gitlab"
	color = "is-link"
    weight = 1
    url = "https://gitlab.com/diazvictor/"
