baseURL = "/"
languageCode = "en-us"
title = "diazvictor"
theme = "blue-ocean"

[params]
author = "VÍCTOR DÍAZ"
description = "dedicado al desarrollo web y aplicaciones, enamorado de lua."
keywords = "blog, developer, personal" # Site keywords.
info = "DESARROLLO WEB Y APLICACIONES"
avatar = "/images/favicon.png"
dateFormat = ""
recent_num = 5

[menu]
	[[menu.item]]
	name = "BLOG"
    url = "/post"
    weight = 1

	[[menu.item]]
	name = "AYUDA"
    url = "/about"
    weight = 2

    [[menu.item]]
	name = "SERVICIOS"
    url = "/services"
    weight = 3

    [[menu.item]]
	name = "PORTOFOLIO"
    url = "/project"
    weight = 4

    [[menu.item]]
	name = "CONTACTOS"
    url = "/contact"
    weight = 5

[params.sidebar]
sidebar = true
widgets = ["aboutbox", "recent", "categories", "taglist"]

[params.widgets]
aboutbox_description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore"
recent_num = 5 # Set the number of articles in the "Recent articles" widget
scrolltop = true
social_footer = true

[[params.project]]
	name = "Lua Less Compiler"
	description = "Lua Less Compiler is a gui frontend for lessc."
	thumbnail = "lua-less-compiler.png"
	url = "http://github.com/diazvictor/lua-less-compiler"
	urlCode = "http://github.com/diazvictor/lua-less-compiler"
	version = "v0.1.0"

[[params.project]]
	name = "Chateando"
	description = "Chateando is a gui frontend for mqtt."
	thumbnail = "chat-mqtt-lua.png"
	url = "https://github.com/diazvictor/chat-mqtt-lua"
	urlCode = "https://github.com/diazvictor/chat-mqtt-lua"
	version = "v0.1.0"

[[params.social]]
	name = "GITLAB"
	icon = "fab fa-gitlab"
	color = "is-link"
    weight = 1
    url = ""

[[params.social]]
	icon = "fab fa-facebook-f"
	color = "is-link"
    weight = 1
    url = ""

[[params.social]]
	icon = "fab fa-telegram"
	color = "is-link"
    weight = 1
    url = ""

[[params.social]]
	icon = "fas fa-envelope"
	color = "is-link"
    weight = 1
    url = ""

