name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update theme
        shell: bash
        run: |
          git config --global user.email "diazvictor@users.noreply.github.com"
          git config --global user.name "diazvictor"
          git submodule update --init --remote
          git add .
          git commit -am "[Bot] Update theme"
          git push --force-with-lease

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public